### ISSUE TITLE
Setup Pi OS images

### ISSUE THREAD

**Issue by mattmahn** [MSOE-Supermileage/DAQ#22]
Requirements:
- start SSH on boot
- make sure GPIO works on starup
- auto-connect to networks
  - MSOE-Guest
  - Wired ethernet
- ensure USB serial works at boot

Make an image for Debian- and Arch Linux-based distros.

**Comment by euclideansphere** [comment]
I put minibian https://minibianpi.wordpress.com/ on the pis and set up ssh keys. Seems to be working as expected, haven't tested gpio

let's get some c++ libraries on these and see how easy it would be to write something useful

**Comment by euclideansphere** [comment]
also - let's try arch too and see what's good
